### PR TITLE
Use keyword argument with MultiIndex.set_levels()

### LINKED ISSUE #16: Fix pandas future warnings
With the current release of `audinterface` we get warnings like:

```
/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/audinterface/core/process.py:127: FutureWarning: In a future version of pandas all arguments of MultiIndex.set_levels except for the argument 'levels' will be keyword-only
30
  y.index = y.index.set_levels([[start], [end]], [1, 2])
```

As this can lead to [failing tests](https://github.com/audeering/opensmile-python/pull/39/checks?check_run_id=2986991383), we should update the code.

### PR DESCRIPTION
**Pull request by frankenjoe**
Closes #16

### CODE REVIEW

**Comment by frankenjoe** [comment]
We now have a another problem:

```
  /home/runner/work/audinterface/audinterface/audinterface/core/feature.py:125: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
```

I don't get the error with `Python 3.6` and latest `numpy`...

**Comment by hagenw** [comment]
We even get an error for our famous time objects:

```
       AssertionError: MultiIndex level [1] are different
341
E       
342
E       MultiIndex level [1] classes are not equivalent
343
E       [left]:  DatetimeIndex(['NaT'], dtype='datetime64[ns]', name='end', freq=None)
344
E       [right]: Float64Index([nan], dtype='float64', name='end')
```

**Comment by frankenjoe** [comment]
> We even get an error for our famous time objects:

yes, seems actually be related to https://github.com/audeering/audinterface/issues/14, so maybe I'll prepare a PR for that issue first.

**Comment by frankenjoe** [comment]
@hagenw cool, after rebasing the error indeed disappeared!

**Comment by hagenw** [comment]
Great, so this now works with Python 3.6 and higher versions.

**Pull request merged**
