### PR TITLE
Release 1.2.3

### PR DESCRIPTION
**Pull request by hagenw**
image

### CODE REVIEW

**Review by ChristianGeng — COMMENTED** [review]
I think the `sibyll` MR was merged later than the 1.2.2 release:

https://github.com/audeering/audinterface/pull/178

**Comment by hagenw** [comment]
Yes, but I did not mention `sybil` as it should not effect the user.

The user is slightly effected as the documentation now looks slightly different. I could add the following:
```
* Changed: use doctest syntax for showing code examples in the documentation
```

Would this be better than stating nothing?

**Comment by ChristianGeng** [comment]
> Yes, but I did not mention `sybil` as it should not effect the user.
> 
> The user is slightly effected as the documentation now looks slightly different. I could add the following:
> 
> ```
> * Changed: use doctest syntax for showing code examples in the documentation
> ```
> 
> Would this be better than stating nothing?

Either: I took the wrong perspective. You are right in saying that it does not affect the user how the docstrings are rendered.  So either of them is fine with me. I will proceed with approval.

**Review by ChristianGeng — APPROVED** [review]
I only had a single minor issue about rendering documentation.
This is settled and I am approving this.

**Pull request merged**
